export enum ErrorCode {
  DATA_FILE_NOT_FOUND = 'DATA_FILE_NOT_FOUND',
  DATA_PARSE_ERROR = 'DATA_PARSE_ERROR',
  DATA_SCHEMA_INVALID = 'DATA_SCHEMA_INVALID',

  SEARCH_INVALID_QUERY = 'SEARCH_INVALID_QUERY',
  SEARCH_MISSING_DEPENDENCIES = 'SEARCH_MISSING_DEPENDENCIES',
  SEARCH_OPERATION_FAILED = 'SEARCH_OPERATION_FAILED',
  SEARCH_INVALID_REGEX = 'SEARCH_INVALID_REGEX',

  VALIDATION_INVALID_PAGINATION = 'VALIDATION_INVALID_PAGINATION',
  VALIDATION_INVALID_OPTIONS = 'VALIDATION_INVALID_OPTIONS',

  TOKENIZATION_MISSING_MORPHOLOGY = 'TOKENIZATION_MISSING_MORPHOLOGY',
  TOKENIZATION_INVALID_MODE = 'TOKENIZATION_INVALID_MODE',

  WORKER_NOT_SUPPORTED = 'WORKER_NOT_SUPPORTED',
  WORKER_INITIALIZATION_FAILED = 'WORKER_INITIALIZATION_FAILED',
  WORKER_TERMINATED = 'WORKER_TERMINATED',
  WORKER_NOT_INITIALIZED = 'WORKER_NOT_INITIALIZED',
  WORKER_FACTORY_ERROR = 'WORKER_FACTORY_ERROR',
}

/**
 * Error types for categorizing errors
 */
export enum ErrorType {
  DATA_ERROR = 'DataError',
  SEARCH_ERROR = 'SearchError',
  VALIDATION_ERROR = 'ValidationError',
  TOKENIZATION_ERROR = 'TokenizationError',
  WORKER_ERROR = 'WorkerError',
}
